name: workshop-nbs-2022
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab>=3
  - jupytext
  - geopandas
  - matplotlib
  - plotly
  - ipywidgets
  - folium
  - ipyleaflet
  - voila=0.3.6

